dist: xenial
language: python
python:
  - "3.7"
install:
  - pip install -r requirements.txt
  - pip install -r tests/test-requirements.txt
script:
  - cd tests && ./run_tests.sh
after_success:
  - cd .. && coveralls
