dist: focal
language: python
python:
  - "3.7"
  - "3.8"
install:
  - pip install -r requirements.txt
  - pip install -r tests/test-requirements.txt
  - pip install fastapi
script:
  - cd tests && ./run-tests.sh
after_success:
  - cd .. && coveralls
